"""
Google Dorking Queries Module
Contains comprehensive list of Google dork queries for security testing
"""

GOOGLE_DORKS = {
    "Information Disclosure": [
        'site:{domain} filetype:pdf',
        'site:{domain} filetype:doc',
        'site:{domain} filetype:docx',
        'site:{domain} filetype:xls',
        'site:{domain} filetype:xlsx',
        'site:{domain} filetype:ppt',
        'site:{domain} filetype:txt',
        'site:{domain} filetype:xml',
        'site:{domain} filetype:conf',
        'site:{domain} filetype:cnf',
        'site:{domain} filetype:reg',
        'site:{domain} filetype:inf',
        'site:{domain} filetype:rdp',
        'site:{domain} filetype:cfg',
        'site:{domain} filetype:log',
        'site:{domain} filetype:bak',
        'site:{domain} filetype:old',
    ],
    
    "Login Pages": [
        'site:{domain} inurl:login',
        'site:{domain} inurl:signin',
        'site:{domain} inurl:admin',
        'site:{domain} inurl:administrator',
        'site:{domain} intitle:"login"',
        'site:{domain} intitle:"admin"',
        'site:{domain} intitle:"administrator"',
        'site:{domain} intitle:"sign in"',
        'site:{domain} "admin panel"',
        'site:{domain} "control panel"',
        'site:{domain} "member login"',
        'site:{domain} "authentication"',
    ],
    
    "Configuration Files": [
        'site:{domain} filetype:env',
        'site:{domain} filetype:config',
        'site:{domain} filetype:ini',
        'site:{domain} filetype:settings',
        'site:{domain} "config.php"',
        'site:{domain} "configuration.php"',
        'site:{domain} "settings.php"',
        'site:{domain} ".htaccess"',
        'site:{domain} "web.config"',
        'site:{domain} "app.config"',
        'site:{domain} "database.yml"',
    ],
    
    "Error Messages": [
        'site:{domain} "error"',
        'site:{domain} "warning"',
        'site:{domain} "fatal error"',
        'site:{domain} "mysql error"',
        'site:{domain} "sql error"',
        'site:{domain} "database error"',
        'site:{domain} "php error"',
        'site:{domain} "apache error"',
        'site:{domain} "nginx error"',
        'site:{domain} "stack trace"',
        'site:{domain} "exception"',
    ],
    
    "Database Files": [
        'site:{domain} filetype:sql',
        'site:{domain} filetype:db',
        'site:{domain} filetype:dbf',
        'site:{domain} filetype:mdb',
        'site:{domain} filetype:sqlite',
        'site:{domain} "database.sql"',
        'site:{domain} "backup.sql"',
        'site:{domain} "dump.sql"',
        'site:{domain} "data.sql"',
    ],
    
    "Directory Listings": [
        'site:{domain} intitle:"index of"',
        'site:{domain} intitle:"directory listing"',
        'site:{domain} intitle:"parent directory"',
        'site:{domain} "index of /"',
        'site:{domain} "index of /admin"',
        'site:{domain} "index of /backup"',
        'site:{domain} "index of /config"',
        'site:{domain} "index of /uploads"',
        'site:{domain} "index of /files"',
    ],
    
    "Sensitive Parameters": [
        'site:{domain} inurl:id=',
        'site:{domain} inurl:user=',
        'site:{domain} inurl:username=',
        'site:{domain} inurl:userid=',
        'site:{domain} inurl:page=',
        'site:{domain} inurl:cat=',
        'site:{domain} inurl:category=',
        'site:{domain} inurl:search=',
        'site:{domain} inurl:query=',
        'site:{domain} inurl:file=',
        'site:{domain} inurl:document=',
        'site:{domain} inurl:root=',
        'site:{domain} inurl:folder=',
        'site:{domain} inurl:path=',
        'site:{domain} inurl:include=',
        'site:{domain} inurl:inc=',
    ],
    
    "Version Information": [
        'site:{domain} "powered by"',
        'site:{domain} "generated by"',
        'site:{domain} "created by"',
        'site:{domain} "version"',
        'site:{domain} "v1." OR "v2." OR "v3."',
        'site:{domain} "apache/" OR "nginx/" OR "iis/"',
        'site:{domain} "wordpress" OR "joomla" OR "drupal"',
        'site:{domain} "phpMyAdmin"',
    ],
    
    "Backup Files": [
        'site:{domain} filetype:bak',
        'site:{domain} filetype:backup',
        'site:{domain} filetype:old',
        'site:{domain} filetype:orig',
        'site:{domain} filetype:tmp',
        'site:{domain} filetype:temp',
        'site:{domain} "backup"',
        'site:{domain} ".bak"',
        'site:{domain} ".old"',
        'site:{domain} ".orig"',
        'site:{domain} "~"',
    ],
    
    "Email Addresses": [
        'site:{domain} "@{domain}"',
        'site:{domain} "email"',
        'site:{domain} "contact"',
        'site:{domain} "mailto:"',
        'site:{domain} filetype:txt "@"',
    ]
}

def get_all_dorks_for_domain(domain):
    """
    Get all Google dork queries for a specific domain
    
    Args:
        domain (str): The target domain
        
    Returns:
        dict: Dictionary with categories and formatted queries
    """
    formatted_dorks = {}
    for category, dorks in GOOGLE_DORKS.items():
        formatted_dorks[category] = [dork.format(domain=domain) for dork in dorks]
    
    return formatted_dorks

def get_dork_count():
    """Get total number of dork queries"""
    return sum(len(dorks) for dorks in GOOGLE_DORKS.values())
