"""
Google Dorking Queries Module
Contains comprehensive list of Google dork queries for security testing
"""

GOOGLE_DORKS = {
    "Document Files": [
        'site:{domain} (filetype:pdf OR filetype:doc OR filetype:docx OR filetype:xls OR filetype:xlsx OR filetype:ppt OR filetype:pptx)',
        'site:{domain} (filetype:txt OR filetype:rtf OR filetype:csv OR filetype:xml OR filetype:json)',
        'site:{domain} (filetype:odt OR filetype:ods OR filetype:odp OR filetype:pages OR filetype:numbers OR filetype:keynote)',
    ],
    
    "Login & Admin Pages": [
        'site:{domain} (inurl:login OR inurl:signin OR inurl:admin OR inurl:administrator OR inurl:dashboard OR inurl:auth)',
        'site:{domain} (intitle:"login" OR intitle:"sign in" OR intitle:"admin" OR intitle:"administrator" OR intitle:"dashboard")',
        'site:{domain} ("admin panel" OR "control panel" OR "member login" OR "authentication" OR "user login")',
    ],
    
    "Configuration Files": [
        'site:{domain} (filetype:env OR filetype:config OR filetype:ini OR filetype:conf OR filetype:cnf OR filetype:cfg)',
        'site:{domain} ("config.php" OR "configuration.php" OR "settings.php" OR ".htaccess" OR "web.config" OR "app.config")',
        'site:{domain} ("database.yml" OR "config.yml" OR "settings.yml" OR "app.yml" OR "docker-compose.yml")',
    ],
    
    "Error & Debug Info": [
        'site:{domain} ("error" OR "warning" OR "fatal error" OR "exception" OR "stack trace")',
        'site:{domain} ("mysql error" OR "sql error" OR "database error" OR "connection failed" OR "query failed")',
        'site:{domain} ("php error" OR "apache error" OR "nginx error" OR "500 internal server error")',
    ],
    
    "Database Files": [
        'site:{domain} (filetype:sql OR filetype:db OR filetype:dbf OR filetype:mdb OR filetype:sqlite)',
        'site:{domain} ("database.sql" OR "backup.sql" OR "dump.sql" OR "data.sql" OR "export.sql")',
        'site:{domain} ("database" OR "dump" OR "backup") (filetype:sql OR filetype:gz OR filetype:tar)',
    ],
    
    "Directory Listings": [
        'site:{domain} (intitle:"index of" OR intitle:"directory listing" OR intitle:"parent directory")',
        'site:{domain} "index of" ("/admin" OR "/backup" OR "/config" OR "/uploads" OR "/files" OR "/logs")',
        'site:{domain} "index of" ("/private" OR "/tmp" OR "/var" OR "/etc" OR "/home")',
    ],
    
    "Vulnerable Parameters": [
        'site:{domain} (inurl:id= OR inurl:user= OR inurl:username= OR inurl:userid= OR inurl:admin=)',
        'site:{domain} (inurl:page= OR inurl:cat= OR inurl:category= OR inurl:search= OR inurl:query=)',
        'site:{domain} (inurl:file= OR inurl:document= OR inurl:root= OR inurl:folder= OR inurl:path=)',
        'site:{domain} (inurl:include= OR inurl:inc= OR inurl:load= OR inurl:show= OR inurl:view=)',
    ],
    
    "Technology Stack": [
        'site:{domain} ("powered by" OR "generated by" OR "created by" OR "built with")',
        'site:{domain} ("wordpress" OR "joomla" OR "drupal" OR "magento" OR "shopify")',
        'site:{domain} ("apache/" OR "nginx/" OR "iis/" OR "tomcat/" OR "php/")',
        'site:{domain} ("version" OR "v1." OR "v2." OR "v3." OR "beta" OR "alpha")',
    ],
    
    "Backup & Temp Files": [
        'site:{domain} (filetype:bak OR filetype:backup OR filetype:old OR filetype:orig OR filetype:tmp)',
        'site:{domain} (filetype:temp OR filetype:swp OR filetype:save OR filetype:cache)',
        'site:{domain} (".bak" OR ".old" OR ".orig" OR ".tmp" OR "~" OR ".backup")',
        'site:{domain} ("backup" OR "archive" OR "copy" OR "duplicate") -inurl:www',
    ],
    
    "Sensitive Info": [
        'site:{domain} ("password" OR "passwd" OR "pwd" OR "secret" OR "key")',
        'site:{domain} ("api_key" OR "apikey" OR "token" OR "auth_token" OR "access_token")',
        'site:{domain} ("username" OR "user" OR "email" OR "mail" OR "contact")',
    ],
    
    "Log Files": [
        'site:{domain} (filetype:log OR filetype:txt) ("error" OR "access" OR "debug")',
        'site:{domain} ("error.log" OR "access.log" OR "debug.log" OR "system.log")',
        'site:{domain} (inurl:log OR inurl:logs) (filetype:txt OR filetype:log)',
    ],
    
    "Cloud & API Info": [
        'site:{domain} ("amazonaws" OR "s3" OR "azure" OR "gcp" OR "digitalocean")',
        'site:{domain} ("api" OR "endpoint" OR "swagger" OR "graphql" OR "rest")',
        'site:{domain} ("docker" OR "kubernetes" OR "jenkins" OR "gitlab" OR "github")',
    ],
    
    "Source Code Files": [
        'site:{domain} (filetype:php OR filetype:asp OR filetype:aspx OR filetype:jsp OR filetype:js OR filetype:css)',
        'site:{domain} (filetype:py OR filetype:rb OR filetype:pl OR filetype:sh OR filetype:bat OR filetype:ps1)',
        'site:{domain} (filetype:java OR filetype:c OR filetype:cpp OR filetype:h OR filetype:cs OR filetype:vb)',
        'site:{domain} (filetype:go OR filetype:rs OR filetype:swift OR filetype:kt OR filetype:scala OR filetype:clj)',
    ],
    
    "Security & Certificates": [
        'site:{domain} (filetype:pem OR filetype:key OR filetype:crt OR filetype:cer OR filetype:p12 OR filetype:pfx)',
        'site:{domain} ("private key" OR "certificate" OR "ssl" OR "tls" OR "rsa" OR "dsa")',
        'site:{domain} ("BEGIN PRIVATE KEY" OR "BEGIN CERTIFICATE" OR "BEGIN RSA PRIVATE KEY")',
        'site:{domain} (filetype:asc OR filetype:gpg OR "BEGIN PGP" OR "ssh-rsa" OR "ssh-dss")',
    ],
    
    "Development & Testing": [
        'site:{domain} (inurl:test OR inurl:staging OR inurl:dev OR inurl:development OR inurl:beta)',
        'site:{domain} ("TODO" OR "FIXME" OR "DEBUG" OR "HACK" OR "XXX" OR "BUG")',
        'site:{domain} (filetype:env OR ".env" OR "environment" OR "local" OR "development")',
        'site:{domain} (inurl:phpinfo OR "phpinfo()" OR "PHP Version" OR "Apache/" OR "Server Information")',
    ],
    
    "Network & Infrastructure": [
        'site:{domain} ("network" OR "subnet" OR "gateway" OR "dns" OR "dhcp" OR "vlan")',
        'site:{domain} (filetype:pcap OR filetype:cap OR "wireshark" OR "tcpdump" OR "packet capture")',
        'site:{domain} ("router" OR "switch" OR "firewall" OR "load balancer" OR "proxy")',
        'site:{domain} ("ip address" OR "mac address" OR "port" OR "service" OR "protocol")',
    ],
    
    "Email & Communications": [
        'site:{domain} ("@" + "{domain}" OR "email" OR "contact" OR "support")',
        'site:{domain} (filetype:eml OR filetype:msg OR filetype:pst OR filetype:ost)',
        'site:{domain} ("smtp" OR "imap" OR "pop3" OR "exchange" OR "outlook")',
        'site:{domain} ("phone" OR "fax" OR "address" OR "location" OR "office")',
    ],
    
    "Passwords & Credentials": [
        'site:{domain} ("password=" OR "pwd=" OR "pass=" OR "passwd=" OR "user=" OR "username=")',
        'site:{domain} (filetype:kdb OR filetype:kdbx OR "keepass" OR "lastpass" OR "1password")',
        'site:{domain} ("default password" OR "admin/admin" OR "admin/password" OR "root/root")',
        'site:{domain} ("login:" OR "password:" OR "user:" OR "account:" OR "credentials")',
    ],
    
    "Sensitive Documents": [
        'site:{domain} ("confidential" OR "classified" OR "restricted" OR "internal" OR "proprietary")',
        'site:{domain} ("contract" OR "agreement" OR "invoice" OR "receipt" OR "statement")',
        'site:{domain} ("social security" OR "ssn" OR "tax" OR "financial" OR "bank")',
        'site:{domain} ("medical" OR "patient" OR "health" OR "insurance" OR "personal")',
    ],
    
    "Git & Version Control": [
        'site:{domain} (inurl:".git" OR "git" OR "repository" OR "repo")',
        'site:{domain} (filetype:gitignore OR ".gitignore" OR ".gitconfig" OR "git-credentials")',
        'site:{domain} ("svn" OR "subversion" OR "mercurial" OR "bazaar" OR "cvs")',
        'site:{domain} ("commit" OR "branch" OR "merge" OR "pull request" OR "diff")',
    ],
    
    "Monitoring & Analytics": [
        'site:{domain} ("analytics" OR "statistics" OR "metrics" OR "monitoring" OR "dashboard")',
        'site:{domain} ("grafana" OR "kibana" OR "elasticsearch" OR "prometheus" OR "nagios")',
        'site:{domain} ("splunk" OR "logstash" OR "fluentd" OR "graylog" OR "syslog")',
        'site:{domain} ("google analytics" OR "gtag" OR "ga(" OR "_gaq" OR "gtm")',
    ]
}

def get_all_dorks_for_domain(domain):
    """
    Get all Google dork queries for a specific domain
    
    Args:
        domain (str): The target domain
        
    Returns:
        dict: Dictionary with categories and formatted queries
    """
    formatted_dorks = {}
    for category, dorks in GOOGLE_DORKS.items():
        formatted_dorks[category] = [dork.format(domain=domain) for dork in dorks]
    
    return formatted_dorks

def get_dork_count():
    """Get total number of dork queries"""
    return sum(len(dorks) for dorks in GOOGLE_DORKS.values())
