"""
Google Dorking Queries Module
Contains comprehensive list of Google dork queries for security testing
"""

GOOGLE_DORKS = {
    "Document Files": [
        'site:{domain} (filetype:pdf OR filetype:doc OR filetype:docx OR filetype:xls OR filetype:xlsx OR filetype:ppt OR filetype:pptx)',
        'site:{domain} (filetype:txt OR filetype:rtf OR filetype:csv OR filetype:xml OR filetype:json)',
    ],
    
    "Login & Admin Pages": [
        'site:{domain} (inurl:login OR inurl:signin OR inurl:admin OR inurl:administrator OR inurl:dashboard OR inurl:auth)',
        'site:{domain} (intitle:"login" OR intitle:"sign in" OR intitle:"admin" OR intitle:"administrator" OR intitle:"dashboard")',
        'site:{domain} ("admin panel" OR "control panel" OR "member login" OR "authentication" OR "user login")',
    ],
    
    "Configuration Files": [
        'site:{domain} (filetype:env OR filetype:config OR filetype:ini OR filetype:conf OR filetype:cnf OR filetype:cfg)',
        'site:{domain} ("config.php" OR "configuration.php" OR "settings.php" OR ".htaccess" OR "web.config" OR "app.config")',
        'site:{domain} ("database.yml" OR "config.yml" OR "settings.yml" OR "app.yml" OR "docker-compose.yml")',
    ],
    
    "Error & Debug Info": [
        'site:{domain} ("error" OR "warning" OR "fatal error" OR "exception" OR "stack trace")',
        'site:{domain} ("mysql error" OR "sql error" OR "database error" OR "connection failed" OR "query failed")',
        'site:{domain} ("php error" OR "apache error" OR "nginx error" OR "500 internal server error")',
    ],
    
    "Database Files": [
        'site:{domain} (filetype:sql OR filetype:db OR filetype:dbf OR filetype:mdb OR filetype:sqlite)',
        'site:{domain} ("database.sql" OR "backup.sql" OR "dump.sql" OR "data.sql" OR "export.sql")',
        'site:{domain} ("database" OR "dump" OR "backup") (filetype:sql OR filetype:gz OR filetype:tar)',
    ],
    
    "Directory Listings": [
        'site:{domain} (intitle:"index of" OR intitle:"directory listing" OR intitle:"parent directory")',
        'site:{domain} "index of" ("/admin" OR "/backup" OR "/config" OR "/uploads" OR "/files" OR "/logs")',
        'site:{domain} "index of" ("/private" OR "/tmp" OR "/var" OR "/etc" OR "/home")',
    ],
    
    "Vulnerable Parameters": [
        'site:{domain} (inurl:id= OR inurl:user= OR inurl:username= OR inurl:userid= OR inurl:admin=)',
        'site:{domain} (inurl:page= OR inurl:cat= OR inurl:category= OR inurl:search= OR inurl:query=)',
        'site:{domain} (inurl:file= OR inurl:document= OR inurl:root= OR inurl:folder= OR inurl:path=)',
        'site:{domain} (inurl:include= OR inurl:inc= OR inurl:load= OR inurl:show= OR inurl:view=)',
    ],
    
    "Technology Stack": [
        'site:{domain} ("powered by" OR "generated by" OR "created by" OR "built with")',
        'site:{domain} ("wordpress" OR "joomla" OR "drupal" OR "magento" OR "shopify")',
        'site:{domain} ("apache/" OR "nginx/" OR "iis/" OR "tomcat/" OR "php/")',
        'site:{domain} ("version" OR "v1." OR "v2." OR "v3." OR "beta" OR "alpha")',
    ],
    
    "Backup & Temp Files": [
        'site:{domain} (filetype:bak OR filetype:backup OR filetype:old OR filetype:orig OR filetype:tmp)',
        'site:{domain} (filetype:temp OR filetype:swp OR filetype:save OR filetype:cache)',
        'site:{domain} (".bak" OR ".old" OR ".orig" OR ".tmp" OR "~" OR ".backup")',
        'site:{domain} ("backup" OR "archive" OR "copy" OR "duplicate") -inurl:www',
    ],
    
    "Sensitive Info": [
        'site:{domain} ("password" OR "passwd" OR "pwd" OR "secret" OR "key")',
        'site:{domain} ("api_key" OR "apikey" OR "token" OR "auth_token" OR "access_token")',
        'site:{domain} ("username" OR "user" OR "email" OR "mail" OR "contact")',
    ],
    
    "Log Files": [
        'site:{domain} (filetype:log OR filetype:txt) ("error" OR "access" OR "debug")',
        'site:{domain} ("error.log" OR "access.log" OR "debug.log" OR "system.log")',
        'site:{domain} (inurl:log OR inurl:logs) (filetype:txt OR filetype:log)',
    ],
    
    "Cloud & API Info": [
        'site:{domain} ("amazonaws" OR "s3" OR "azure" OR "gcp" OR "digitalocean")',
        'site:{domain} ("api" OR "endpoint" OR "swagger" OR "graphql" OR "rest")',
        'site:{domain} ("docker" OR "kubernetes" OR "jenkins" OR "gitlab" OR "github")',
    ]
}

def get_all_dorks_for_domain(domain):
    """
    Get all Google dork queries for a specific domain
    
    Args:
        domain (str): The target domain
        
    Returns:
        dict: Dictionary with categories and formatted queries
    """
    formatted_dorks = {}
    for category, dorks in GOOGLE_DORKS.items():
        formatted_dorks[category] = [dork.format(domain=domain) for dork in dorks]
    
    return formatted_dorks

def get_dork_count():
    """Get total number of dork queries"""
    return sum(len(dorks) for dorks in GOOGLE_DORKS.values())
